### ISSUE TITLE
Android_demo always have a crash in android 6.0 platform

### ISSUE THREAD

**Issue by leochangzliao** [ksvc/ks265codec#30]
I guess the demo don't  apply dynamic permission of sdcard.

**Comment by zhangxianguo** [comment]
Do you mean your yuvs are stored in the sdcard?

**Comment by leochangzliao** [comment]
yes,its absolute path is like /sdcard/my.yuv

**Comment by sujia** [comment]
we don't have this problem on our android 6.0 devices.  could you provide more info ?  the crash log ?

**Comment by zhangxianguo** [comment]
or the yuv downloading address

**Comment by leochangzliao** [comment]
your yuv link : [https://github.com/ksvc/ks265codec/blob/master/iOS_demo/resource/640x480_15.yuv](url)

here the crash log follows:     (just click "浏览文件" button)

`06-30 11:36:41.645 10972-11341/com.ksyun.media.ksy265codec.demo E/art: JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal continuation byte 0
06-30 11:36:41.645 10972-11341/com.ksyun.media.ksy265codec.demo E/art:     string: '新建文本文�'
06-30 11:36:41.645 10972-11341/com.ksyun.media.ksy265codec.demo E/art:     in call to NewStringUTF
06-30 11:36:41.645 10972-11341/com.ksyun.media.ksy265codec.demo E/art:     from java.lang.String[] java.io.File.listImpl(java.lang.String)
06-30 11:36:41.645 10972-11341/com.ksyun.media.ksy265codec.demo E/art: "ModernAsyncTask #1" prio=5 tid=21 Runnable
06-30 11:36:41.645 10972-11341/com.ksyun.media.ksy265codec.demo E/art:   | group="main" sCount=0 dsCount=0 obj=0x32e18be0 self=0xdc52e800
06-30 11:36:41.645 10972-11341/com.ksyun.media.ksy265codec.demo E/art:   | sysTid=11341 nice=10 cgrp=bg_non_interactive sched=0/0 handle=0xda626930
06-30 11:36:41.645 10972-11341/com.ksyun.media.ksy265codec.demo E/art:   | state=R schedstat=( 510692 39846 3 ) utm=0 stm=0 core=2 HZ=100
06-30 11:36:41.645 10972-11341/com.ksyun.media.ksy265codec.demo E/art:   | stack=0xda524000-0xda526000 stackSize=1038KB
06-30 11:36:41.645 10972-11341/com.ksyun.media.ksy265codec.demo E/art:   | held mutexes= "mutator lock"(shared held)
06-30 11:36:41.645 10972-11341/com.ksyun.media.ksy265codec.demo E/art:     at java.io.File.listImpl(Native method)
06-30 11:36:41.645 10972-11341/com.ksyun.media.ksy265codec.demo E/art:     at java.io.File.list(File.java:740)
06-30 11:36:41.646 10972-11341/com.ksyun.media.ksy265codec.demo E/art:     at java.io.File.listFiles(File.java:782)
06-30 11:36:41.646 10972-11341/com.ksyun.media.ksy265codec.demo E/art:     at java.io.File.listFiles(File.java:817)
06-30 11:36:41.646 10972-11341/com.ksyun.media.ksy265codec.demo E/art:     at com.ipaulpro.afilechooser.FileLoader.loadInBackground(FileLoader.java:62)
06-30 11:36:41.646 10972-11341/com.ksyun.media.ksy265codec.demo E/art:     at com.ipaulpro.afilechooser.FileLoader.loadInBackground(FileLoader.java:36)
06-30 11:36:41.646 10972-11341/com.ksyun.media.ksy265codec.demo E/art:     at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:299)
06-30 11:36:41.646 10972-11341/com.ksyun.media.ksy265codec.demo E/art:     at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
06-30 11:36:41.646 10972-11341/com.ksyun.media.ksy265codec.demo E/art:     at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:45)
06-30 11:36:41.646 10972-11341/com.ksyun.media.ksy265codec.demo E/art:     at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
06-30 11:36:41.646 10972-11341/com.ksyun.media.ksy265codec.demo E/art:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-30 11:36:41.646 10972-11341/com.ksyun.media.ksy265codec.demo E/art:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
06-30 11:36:41.646 10972-11341/com.ksyun.media.ksy265codec.demo E/art:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
06-30 11:36:41.646 10972-11341/com.ksyun.media.ksy265codec.demo E/art:     at java.lang.Thread.run(Thread.java:818)`

**Comment by sujia** [comment]
it seems crashed when navigate folders on your sdcard.  there are files named with invalid UTF-8 characters.
 you could delete the files like '新建文本文�' to workaround.

**Comment by leochangzliao** [comment]
@sujia I have deleted all files named with invalid UTF-8 characters,but still got a crash and the log is same as above.

**Comment by zhangxianguo** [comment]
@zldada @sujia can you make connections using QQ or wechat?
